---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: alex-pipeline82
  name: ui-alex-pipeline82
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-develop-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: alex-pipeline82
  name: ui
  namespace: ui-alex-pipeline82
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: ui
  values:
    biomageCi:
      repo: biomage-ltd/ui
      sandboxId: alex-pipeline82
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-develop-fc5c4483688cfef5ad6200c42abe1f378a3c0fdd
    kubernetes:
      env: staging
    livenessProbe:
      path: /data-management
    readinessProbe:
      path: /data-management
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: alex-pipeline82
  name: api-alex-pipeline82
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-develop-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: alex-pipeline82
  name: api
  namespace: api-alex-pipeline82
spec:
  chart:
    git: git@github.com:biomage-ltd/iac
    path: charts/nodejs
    ref: 135cdd67171877da40b8f3318b14a29517ee2f35
  releaseName: api
  values:
    biomageCi:
      repo: biomage-ltd/api
      sandboxId: alex-pipeline82
    hpa:
      enabled: true
      maxReplicas: 10
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-develop-8f94c073f31f2d043c669c1354207cb7d5b34e56
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      path: /v1/health
    readinessProbe:
      path: /v1/health
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: alex-pipeline82
  name: worker-alex-pipeline82
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-develop-*-python
    filter.fluxcd.io/r: glob:refs-heads-develop-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: alex-pipeline82
  name: worker
  namespace: worker-alex-pipeline82
spec:
  chart:
    git: git@github.com:biomage-ltd/worker
    path: chart-infra/
    ref: 6b6a2d26a1269bab963c354a9bbc283bceb405ba
  releaseName: worker
  values:
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-develop-6b6a2d26a1269bab963c354a9bbc283bceb405ba-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-develop-6b6a2d26a1269bab963c354a9bbc283bceb405ba-r
    sandboxId: alex-pipeline82
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: alex-pipeline82
  name: pipeline-alex-pipeline82
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipeline-runner: glob:refs-pull-82-merge-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: alex-pipeline82
  name: pipeline
  namespace: pipeline-alex-pipeline82
spec:
  chart:
    git: git@github.com:biomage-ltd/pipeline
    path: chart-infra/
    ref: refs/pull/82/head
  releaseName: pipeline
  values:
    pipeline-runner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-82-merge-ee78ee507dd2f43aba05bbd8517246ccb496970f-pipeline-runner
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
